name: Publish NuGet packages

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set MINVERBUILDMETADATA
      run: echo MINVERBUILDMETADATA=$(git rev-parse --short ${GITHUB_SHA})  >> $GITHUB_ENV
    - name: Build
      run: dotnet build  --configuration Release --no-restore
    - name: Publish to Github Packages
      run: |
          for nupkg in $(find . -name *.nupkg)
          do
            echo Pushing $nupkg
            dotnet nuget push $nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done
